const I18N = {
    vi: {
        // --- INDEX ---
        "idx_title": "🎮 ECONOVA SHOW 2026",
        "idx_subtitle": "Hệ thống thi đấu trực tuyến",
        "idx_sec1": "Điều khiển & Hiển thị",
        "idx_admin": "🖥️ Kỹ thuật viên",
        "idx_admin_desc": "Điều khiển trò chơi",
        "idx_screen": "📺 Màn hình đồ họa",
        "idx_screen_desc": "Hiển thị cho khán giả",
        "idx_scoreboard": "📊 Bảng điểm",
        "idx_scoreboard_desc": "Hiển thị điểm 4 đội",
        "idx_sec2": "Máy thí sinh (Chọn đội khi vào)",
        "idx_contestant": "📱 Máy thí sinh",
        "idx_contestant_desc": "Mở trên 4 máy riêng biệt",

        // --- ADMIN ---
        "adm_title": "Econova Show - Bảng Điều Khiển",
        "adm_sec1": "1. Danh sách đội thi",
        "adm_sec2": "2. Chọn ngân hàng đề",
        "adm_sec3": "3. Bảng điều khiển chính",
        "adm_sec4": "4. Điều khiển luồng chơi",
        "adm_sec5": "5. Bảng điểm & Chỉnh thủ công",
        "adm_sec6": "6. Cài đặt Đồ hoạ (Themes)",
        "adm_flow_control": "⚡ 4. Điều khiển luồng chơi",
        "adm_turn_order": "📋 Thứ tự lượt chơi hiện tại:",
        "adm_end_turn_prefix": "🏁 KẾT THÚC PHẦN CHƠI CỦA: ",
        "adm_end_turn_default": "🏁 KẾT THÚC PHẦN CHƠI CHO ĐỘI HIỆN TẠI",
        "adm_end_turn": "🏁 KẾT THÚC PHẦN CHƠI CHO ĐỘI HIỆN TẠI",
        "adm_current_q": "📝 Câu hỏi đang hiển thị:",
        "adm_ans": "💡 Đáp án:",
        "adm_video": "🎥 Video đính kèm:",
        "adm_play": "▶️ PHÁT VIDEO",
        "adm_close": "❌ ĐÓNG VIDEO",
        "adm_timer": "⏱ Đếm ngược:",
        "adm_back": "🔙 ĐÓNG CÂU HỎI & TRỞ VỀ BẢNG CHỌN",
        "adm_team_act": "Đội chính:",
        "adm_hopestar": "⭐ BẬT NS HY VỌNG",
        "adm_open_q": "🚀 MỞ CÂU HỎI",
        "adm_grid_show": "🟢 MỞ GÓI ĐIỂM",
        "adm_grid_hide": "🔴 ĐÓNG GÓI ĐIỂM",
        "adm_room_closed": "ĐÃ ĐÓNG",
        "adm_network_creating": "ĐANG TẠO KẾT NỐI... (",
        "adm_network_err": "❌ Lỗi tạo mạng: ",
        "adm_network_btn": "🌐 TẠO SERVER NGROK",
        "adm_cd_15": "⏱ ĐẾM NGƯỢC 15S (CÂU THƯỜNG)",
        "adm_cd_10": "⏱ ĐẾM NGƯỢC 10S (CÓ VIDEO)",
        "adm_close_q": "🔙 ĐÓNG CÂU HỎI & TRỞ VỀ BẢNG CHỌN",
        "adm_correct": "✅ ĐÚNG (Cộng 100%)",
        "adm_wrong": "❌ SAI (Trừ 50%, mở chuông)",
        "adm_waiting": "ĐANG CHỜ...",
        "adm_q_selected": "CÂU HỎI ĐÃ CHỌN",
        "adm_q_resolved": "✅ CÂU HỎI ĐÃ ĐƯỢC GIẢI QUYẾT.",
        "adm_buzz_team": "Đội giành quyền: ",
        "adm_buzzed": "Đội giành quyền:",
        "adm_buzz_table_title": "Thứ tự bấm chuông:",
        "adm_buzz_time": "Thứ tự bấm chuông:",
        "adm_rank": "Hạng",
        "adm_team": "Đội",
        "adm_time": "Thời gian",
        "adm_pts": "ĐIỂM",
        "adm_theme": "Giao diện (Theme):",
        "adm_lang": "Ngôn ngữ hiển thị (Language):",
        "adm_bright": "Độ sáng Màn hình",
        "adm_scale": "Độ thu phóng Kích cỡ",
        "adm_anticheat": "Chống gian lận (Máy thí sinh):",
        "adm_reset": "🔄 RESET GAME",
        "adm_header_title": "🖥️ Hệ thống điều khiển - Kỹ thuật viên",
        "adm_tab_main": "🎮 VÒNG 2 (CHỨC NĂNG CHÍNH)",
        "adm_tab_settings": "⚙️ CÀI ĐẶT & KHÁC",
        "adm_network_title": "🌍 Điều Khiển Mạng Ngoại & Phòng Thi",
        "adm_lan_title": "1. MẠNG LAN / VPN (KHUYÊN DÙNG)",
        "adm_lan_desc": "Dùng khi kết nối chung WiFi hoặc ứng dụng VPN (Radmin VPN, Hamachi...)",
        "adm_ip_loading": "⏳ Đang tải IP...",
        "adm_public_title": "2. KẾT NỐI MẠNG NGOÀI (PUBLIC SERVER)",
        "adm_public_desc": "Tạo link public bằng Localtunnel (Miễn phí - Không giới hạn).",
        "adm_ngrok_auth": "Ngrok Authtoken (Lấy tại dashboard.ngrok.com/get-started/your-authtoken)",
        "adm_ngrok_domain": "Ngrok Static Domain (Tuỳ chọn: ví dụ thu-nghiem.ngrok-free.app)",
        "adm_ngrok_btn": "🌐 TẠO SERVER LOCALTUNNEL",
        "adm_ngrok_success": "✅ Đã kết nối thành công:",
        "adm_ngrok_link": "Link truy cập:",
        "adm_room_title": "3. TRẠNG THÁI PHÒNG THI",
        "adm_room_desc": "Thí sinh cần nhập Mã PIN để tham gia thi đấu.",
        "adm_room_pin": "Mã PIN: ",
        "adm_room_status": "Trạng thái: ",
        "adm_room_closed": "ĐÃ ĐÓNG",
        "adm_room_open": "🟢 MỞ PHÒNG",
        "adm_room_close": "🔴 ĐÓNG PHÒNG",
        "adm_teams_title": "👥 1. Thông tin các đội thi",
        "adm_teams_save": "💾 LƯU THÔNG TIN ĐỘI",
        "adm_bank_title": "📁 2. Ngân hàng câu hỏi",
        "adm_bank_import": "📥 Nhập từ file Excel:",
        "adm_bank_load": "📤 TẢI DỮ LIỆU",
        "adm_bank_empty": "Chưa tải file.",
        "adm_bank_save_to": "💾 Lưu bộ đề hiện tại vào thư mục:",
        "adm_bank_slot_1": "Đề 1",
        "adm_bank_slot_2": "Đề 2",
        "adm_bank_slot_3": "Đề 3",
        "adm_bank_slot_4": "Đề 4",
        "adm_bank_slot_5": "Đề 5",
        "adm_bank_slot_6": "Đề 6",
        "adm_bank_save_name": "Tên bộ đề (VD: Vòng chung kết)",
        "adm_bank_save_btn": "💾 LƯU",
        "adm_bank_load_from": "📂 Tải bộ đề đã lưu:",
        "adm_qset_title": "🎯 3. Cài đặt câu hỏi tiếp theo",
        "adm_qset_main": "Đội chính:",
        "adm_qset_auto": "-- Tự động theo Lượt --",
        "adm_qset_t1": "Đội 1",
        "adm_qset_t2": "Đội 2",
        "adm_qset_t3": "Đội 3",
        "adm_qset_t4": "Đội 4",
        "adm_qset_pts": "Gói điểm:",
        "adm_qset_p10": "10đ (Dễ)",
        "adm_qset_p20": "20đ (Trung bình)",
        "adm_qset_p40": "40đ (Khó)",
        "adm_qset_select": "Chọn câu:",
        "adm_qset_manual": "-- Thủ công --",
        "adm_qmode": "Chế độ chọn câu:",
        "adm_qmode_1": "1 - Từng câu một",
        "adm_qmode_2": "2 - Cả gói (Chọn thứ tự)",
        "adm_qmode_3": "3 - Cả gói (Ngẫu nhiên)",
        "adm_lock_pkg": "🔒 CHỐT GÓI CÂU HỎI",
        "adm_next_q": "⏭️ CHUYỂN CÂU",
        "adm_sb_main_title": "🏆 6. Bảng Điểm Tổng Hợp (Màn hình chính)",
        "adm_sb_show": "👁️ HIỂN THỊ BẢNG ĐIỂM TỔNG LÊN MÀN HÌNH",
        "adm_sb_bg": "Thay đổi hình nền Bảng Điểm (Tùy chọn):",
        "adm_sb_title_inp": "📝 Tiêu đề Bảng Điểm (để trống = không hiển thị):",
        "adm_sb_title_ph": "VD: KẾT QUẢ CHUNG CUỘC",
        "adm_sb_y": "Vị trí dọc Y (",
        "adm_sb_size": "📷 Cỡ ảnh chung (",
        "adm_sb_overlap": "⬇️ Che tên chung (",
        "adm_sb_offsetx": "↔️ Lệch ngang chung (",
        "adm_sb_apply_all": "ÁP DỤNG TẤT CẢ",
        "adm_sb_font_team": "Font Tên Đội:",
        "adm_sb_font_score": "Font Điểm Số:",
        "adm_sb_preview": "👁 Preview Bảng Điểm:",
        "adm_sb_preview_hint": "Bật Bảng Điểm để xem preview.",
        "adm_theme_classic": "Cổ điển (Vũ trụ)",
        "adm_theme_ascend": "Ascend 2026 (Mới)",
        "adm_theme_v3": "Hiệu ứng Bay Lượn (V3)",
        "adm_lang_vi": "Tiếng Việt",
        "adm_lang_en": "English",
        "adm_ac_off": "TẮT (Chế độ Test)",
        "adm_ac_on": "BẬT (Thi đấu chính thức)",
        "adm_team_cnt": "⚠️ Số lượng Đội thi:",
        "adm_team_2": "2 Đội",
        "adm_team_3": "3 Đội",
        "adm_team_4": "4 Đội",
        "adm_team_6": "6 Đội",
        "adm_tr_seq": "Theo thứ tự đội (1 -> {X})",
        "adm_tr_desc": "Theo điểm: Cao đến Thấp",
        "adm_tr_asc": "Theo điểm: Thấp đến Cao",
        "adm_team_note": "Lưu ý: Thay đổi sẽ Reset toàn bộ điểm số và câu hỏi.",
        "adm_team_q_cnt": "Số câu hỏi mỗi đội:",
        "adm_team_q_save": "LƯU",
        "adm_team_max": "(Tối đa: ",
        "adm_err_auth": "Lỗi xác thực Admin hoặc Mã PIN đã đổi! Vui lòng đăng nhập lại.",
        "adm_err_excel": "Chọn file Excel trước!",
        "adm_excel_ok": "✅ Tải thành công: {10} Dễ, {20} TB, {40} Khó.",
        "adm_excel_err": "Lỗi đọc Excel: ",
        "adm_save_empty": "Chưa có dữ liệu câu hỏi nào để lưu!",
        "adm_save_name_prefix": "Đề ",
        "adm_save_ok": "Đã lưu thành công vào Đề {slotId}!",
        "adm_save_err": "Lỗi lưu: ",
        "adm_load_empty": "Slot trống",
        "adm_load_ok": "📂 Đã tải \"{name}\": {10} Dễ, {20} TB, {40} Khó.",
        "adm_load_err": "Lỗi: ",
        "adm_slot_txt": "{10} Dễ, {20} TB, {40} Khó",
        "adm_slot_empty": "Trống",
        "adm_slot_btn": "📂 Tải",
        "adm_q_label": "Câu {stt}",
        "adm_q_played": " (ĐÃ CHỌN)",
        "adm_star_added": " NGÔI SAO HY VỌNG ⭐",
        "adm_err_q": "Lỗi khi bấm Lên câu hỏi: ",
        "adm_err_not_enough_q": "Bộ đề hiện tại không đủ câu hỏi! Mỗi đội chỉ được tối đa {max} câu.",
        "adm_confirm_reset": "Reset toàn bộ điểm?",
        "adm_confirm_team_cnt": "Thay đổi số lượng đội thi sẽ RESET toàn bộ game (điểm số, trạng thái). Bạn có chắc chắn?",
        "adm_opt_optional": "(Tuỳ chọn)",
        "adm_placeholder_tname": "Tên đội {id}",
        "adm_placeholder_tschool": "Trường / Đơn vị {id}",
        "adm_label_tavatar": "Thay ảnh đội {id}:",
        "adm_ts_size": "Đội {id} - Cỡ ảnh (",
        "adm_ts_overlap": "Che tên (",
        "adm_ts_offsetx": "Lệch ngang (",
        "adm_sel_team": "-- Chọn đội --",
        "adm_to_played": " (Đã chơi)",
        "adm_to_force": "Ép chơi",
        "adm_to_end": "Kết thúc",
        "adm_to_stats": "[Đã chơi {played}/{total} câu]",
        "adm_empty": "(Trống)",
        "adm_status_buzz_team": "🚨 {team} GIÀNH QUYỀN TRẢ LỜI",
        "adm_status_buzz_open": "🟢 ĐANG MỞ CHUÔNG 5S",
        "adm_status_play": "ĐANG THI: {team} ({pts}Đ)",
        "adm_status_star": "⭐ NSHV",
        "adm_status_star_only": "ĐÃ CHỌN NGÔI SAO HY VỌNG ⭐",
        "adm_pt_ph": "Nhập điểm...",
        "adm_pt_add": "CỘNG",
        "adm_pt_sub": "TRỪ",
        "adm_sb_hide": "🚫 ẨN BẢNG ĐIỂM TỔNG",
        "adm_err_ngrok_auth": "Vui lòng nhập Ngrok Authtoken! (Đăng ký miễn phí tại ngrok.com)",
        "adm_ip_none": "Không tìm thấy IP cục bộ.",
        "adm_net_err": "Lỗi tạo mạng: ",
        "adm_font_pop": "── Font phổ biến ──",
        "adm_font_all": "── Tất cả font trong máy ──",
        "adm_font_custom": " (tùy chỉnh)",
        "adm_modal_title": "Thông báo",
        "adm_modal_ok": "✅ ĐỒNG Ý",
        "adm_modal_cancel": "❌ HỦY",

        // --- SCREEN / OVERLAY ---
        "scr_title": "Econova Show - Màn Hình Chính",
        "scr_audio_start": "🔊 BẤM VÀO ĐÂY ĐỂ BẮT ĐẦU",
        "scr_pts": "ĐIỂM",
        "scr_wait": "Đang chờ câu hỏi...",
        "scr_click_start": "👇 BẤM VÀO ĐÂY ĐỂ BẮT ĐẦU",
        "scr_unlock_audio": "Thao tác này giúp mở khoá hệ thống âm thanh của trình duyệt.",
        "scr_round": "ROUND 3.2: MYSTERY BOX",
        "scr_pts_empty": "-- ĐIỂM",
        "scr_pts_empty_1": "- ĐIỂM",
        "scr_pts_10": "10 ĐIỂM",
        "scr_pts_20": "20 ĐIỂM",
        "scr_pts_40": "40 ĐIỂM",

        // --- CONTESTANT ---
        "con_choose": "CHỌN ĐỘI CỦA BẠN",
        "con_buzz": "🔔 BẤM CHUÔNG",
        "con_locked": "CHUÔNG KHÓA",
        "con_other": "ĐỘI KHÁC ĐÃ GIÀNH QUYỀN",
        "con_you": "BẠN ĐÃ GIÀNH QUYỀN TRẢ LỜI!",
        "con_wait_admin": "Đang chờ admin cấp quyền...",
        "con_cheat_title": "🚨 CẢNH BÁO GIAN LẬN!",
        "con_cheat_desc": "Bạn đã rời khỏi màn hình thi hoặc bấm nhầm phím cấm. Thao tác này đã bị chặn lại.",
        "con_cheat_btn": "TÔI ĐÃ HIỂU",
        "con_click_start": "BẤM VÀO ĐÂY ĐỂ BẮT ĐẦU",
        "con_req_full": "Yêu cầu bật chế độ Toàn Màn Hình",
        "con_no_buzz": "BẠN KHÔNG ĐƯỢC BẤM",
        "con_title": "Econova Show - Thí Sinh",
        "con_access_denied": "Truy cập bị từ chối. Vui lòng mở ứng dụng từ file chạy chính (.exe).",
        "con_pts_10": "10 ĐIỂM",
        "con_pts_20": "20 ĐIỂM",
        "con_pts_40": "40 ĐIỂM",
        "con_claimed": " (Đã chọn)",
        "con_session_ended": "Phiên thi đấu đã kết thúc hoặc Mã PIN đã thay đổi. Vui lòng đóng ứng dụng và mở lại!",
        "con_team_count_changed": "Ban tổ chức đã thay đổi số lượng đội thi. Vui lòng chọn lại đội!",
        "con_buzz_open": "CHUÔNG ĐÃ MỞ!",
        "con_buzz_exclaim": "🔔 BẤM CHUÔNG!",
        "con_team_placeholder": "TEAM",
        "con_school_placeholder": "Trường",
        "con_your_turn": "LƯỢT CỦA BẠN",

        // --- SCOREBOARD ---
        "sb_choose": "CHỌN ĐỘI BẢNG ĐIỂM",
        "sb_title": "BẢNG ĐIỂM CÁ NHÂN",
        "sb_page_title": "Econova Show - Bảng Điểm",
        "sb_access_denied": "Truy cập bị từ chối. Vui lòng mở ứng dụng từ file chạy chính (.exe).",
        "sb_team_count_changed": "Ban tổ chức đã thay đổi số lượng đội thi. Vui lòng chọn lại đội!"
    },
    en: {
        // --- INDEX ---
        "idx_title": "🎮 ECONOVA SHOW 2026",
        "idx_subtitle": "Online Competition System",
        "idx_sec1": "Control & Display",
        "idx_admin": "🖥️ Technician",
        "idx_admin_desc": "Game Controller",
        "idx_screen": "📺 Main Screen",
        "idx_screen_desc": "Display for Audience",
        "idx_scoreboard": "📊 Scoreboard",
        "idx_scoreboard_desc": "Display 4 Teams' Scores",
        "idx_sec2": "Contestant Device (Select team upon entry)",
        "idx_contestant": "📱 Contestant Device",
        "idx_contestant_desc": "Open on 4 separate devices",

        // --- ADMIN ---
        "adm_title": "Econova Show - Control Panel",
        "adm_sec1": "1. Teams List",
        "adm_sec2": "2. Select Question Bank",
        "adm_sec3": "3. Main Control Panel",
        "adm_sec4": "4. Game Flow Control",
        "adm_sec5": "5. Scoreboard & Manual Edit",
        "adm_sec6": "6. Graphic Settings (Themes)",
        "adm_flow_control": "⚡ 4. Game Flow Control",
        "adm_turn_order": "📋 Current Turn Order:",
        "adm_end_turn_prefix": "🏁 END TURN FOR: ",
        "adm_end_turn_default": "🏁 END CURRENT TURN",
        "adm_end_turn": "🏁 END CURRENT TURN",
        "adm_current_q": "📝 Current Question:",
        "adm_ans": "💡 Answer:",
        "adm_video": "🎥 Attached Video:",
        "adm_play": "▶️ PLAY VIDEO",
        "adm_close": "❌ CLOSE VIDEO",
        "adm_timer": "⏱ Countdown:",
        "adm_back": "🔙 CLOSE QUESTION & RETURN",
        "adm_team_act": "Main Team:",
        "adm_hopestar": "⭐ TOGGLE HOPE STAR",
        "adm_open_q": "🚀 OPEN QUESTION",
        "adm_grid_show": "🟢 MỞ GÓI ĐIỂM",
        "adm_grid_hide": "🔴 ĐÓNG GÓI ĐIỂM",
        "adm_room_closed": "CLOSED",
        "adm_network_creating": "CREATING CONNECTION... (",
        "adm_network_err": "❌ Network error: ",
        "adm_network_btn": "🌐 CREATE NGROK SERVER",
        "adm_cd_15": "⏱ 15S COUNTDOWN (NORMAL)",
        "adm_cd_10": "⏱ 10S COUNTDOWN (VIDEO)",
        "adm_close_q": "🔙 CLOSE QUESTION & RETURN",
        "adm_correct": "✅ CORRECT (+100%)",
        "adm_wrong": "❌ WRONG (-50%, unlock buzzer)",
        "adm_waiting": "WAITING...",
        "adm_q_selected": "SELECTED QUESTION",
        "adm_q_resolved": "✅ QUESTION HAS BEEN RESOLVED.",
        "adm_buzz_team": "Buzzed team: ",
        "adm_buzzed": "Buzzed team:",
        "adm_buzz_table_title": "Buzz order:",
        "adm_buzz_time": "Buzz order:",
        "adm_rank": "Rank",
        "adm_team": "Team",
        "adm_time": "Time",
        "adm_pts": "PTS",
        "adm_theme": "Theme:",
        "adm_lang": "Language:",
        "adm_bright": "Screen Brightness",
        "adm_scale": "Scale Size",
        "adm_anticheat": "Anti-cheat (Contestant):",
        "adm_reset": "🔄 RESET GAME",
        "adm_header_title": "🖥️ Control System - Technician",
        "adm_tab_main": "🎮 ROUND 2 (MAIN FUNCTIONS)",
        "adm_tab_settings": "⚙️ SETTINGS & OTHERS",
        "adm_network_title": "🌍 Network & Room Control",
        "adm_lan_title": "1. LAN / VPN (RECOMMENDED)",
        "adm_lan_desc": "Use when sharing WiFi or using VPN apps (Radmin VPN, Hamachi...)",
        "adm_ip_loading": "⏳ Loading IPs...",
        "adm_public_title": "2. PUBLIC CONNECTION (SERVER)",
        "adm_public_desc": "Create a public link using Localtunnel (Free - Unlimited bandwidth).",
        "adm_ngrok_auth": "Ngrok Authtoken (Get from dashboard.ngrok.com/get-started/your-authtoken)",
        "adm_ngrok_domain": "Ngrok Static Domain (Optional: e.g. thu-nghiem.ngrok-free.app)",
        "adm_ngrok_btn": "🌐 CREATE LOCALTUNNEL SERVER",
        "adm_ngrok_success": "✅ Successfully connected:",
        "adm_ngrok_link": "Access link:",
        "adm_room_title": "3. ROOM STATUS",
        "adm_room_desc": "Contestants need a PIN code to join the competition.",
        "adm_room_pin": "PIN Code: ",
        "adm_room_status": "Status: ",
        "adm_room_closed": "CLOSED",
        "adm_room_open": "🟢 OPEN ROOM",
        "adm_room_close": "🔴 CLOSE ROOM",
        "adm_teams_title": "👥 1. Teams Information",
        "adm_teams_save": "💾 SAVE TEAMS INFO",
        "adm_bank_title": "📁 2. Question Bank",
        "adm_bank_import": "📥 Import from Excel:",
        "adm_bank_load": "📤 LOAD DATA",
        "adm_bank_empty": "No file loaded.",
        "adm_bank_save_to": "💾 Save current set to slot:",
        "adm_bank_slot_1": "Set 1",
        "adm_bank_slot_2": "Set 2",
        "adm_bank_slot_3": "Set 3",
        "adm_bank_slot_4": "Set 4",
        "adm_bank_slot_5": "Set 5",
        "adm_bank_slot_6": "Set 6",
        "adm_bank_save_name": "Set name (e.g. Final Round)",
        "adm_bank_save_btn": "💾 SAVE",
        "adm_bank_load_from": "📂 Load saved set:",
        "adm_qset_title": "🎯 3. Setup next question",
        "adm_qset_main": "Main Team:",
        "adm_qset_auto": "-- Auto by Turn --",
        "adm_qset_t1": "Team 1",
        "adm_qset_t2": "Team 2",
        "adm_qset_t3": "Team 3",
        "adm_qset_t4": "Team 4",
        "adm_qset_pts": "Points:",
        "adm_qset_p10": "10pts (Easy)",
        "adm_qset_p20": "20pts (Medium)",
        "adm_qset_p40": "40pts (Hard)",
        "adm_qset_select": "Select question:",
        "adm_qset_manual": "-- Manual --",
        "adm_qmode": "Selection Mode:",
        "adm_qmode_1": "1 - One by one",
        "adm_qmode_2": "2 - Full Package (Specific order)",
        "adm_qmode_3": "3 - Full Package (Random)",
        "adm_lock_pkg": "🔒 LOCK PACKAGE",
        "adm_next_q": "⏭️ NEXT QUESTION",
        "adm_sb_main_title": "🏆 6. Overall Scoreboard (Main Screen)",
        "adm_sb_show": "👁️ DISPLAY OVERALL SCOREBOARD TO SCREEN",
        "adm_sb_bg": "Change Scoreboard Background (Optional):",
        "adm_sb_title_inp": "📝 Scoreboard Title (leave blank = hide):",
        "adm_sb_title_ph": "e.g. FINAL RESULTS",
        "adm_sb_y": "Vertical Y Position (",
        "adm_sb_size": "📷 Base Size (",
        "adm_sb_overlap": "⬇️ Base Overlap (",
        "adm_sb_offsetx": "↔️ Base X Offset (",
        "adm_sb_apply_all": "APPLY TO ALL",
        "adm_sb_font_team": "Team Name Font:",
        "adm_sb_font_score": "Score Font:",
        "adm_sb_preview": "👁 Scoreboard Preview:",
        "adm_sb_preview_hint": "Turn on Scoreboard to see preview.",
        "adm_theme_classic": "Classic (Space)",
        "adm_theme_ascend": "Ascend 2026 (New)",
        "adm_theme_v3": "Flying UI (V3)",
        "adm_lang_vi": "Tiếng Việt",
        "adm_lang_en": "English",
        "adm_ac_off": "OFF (Test Mode)",
        "adm_ac_on": "ON (Official Competition)",
        "adm_team_cnt": "⚠️ Number of Teams:",
        "adm_team_2": "2 Teams",
        "adm_team_3": "3 Teams",
        "adm_team_4": "4 Teams",
        "adm_team_6": "6 Teams",
        "adm_tr_seq": "Sequential (1 -> {X})",
        "adm_tr_desc": "By Score: High to Low",
        "adm_tr_asc": "By Score: Low to High",
        "adm_team_note": "Note: Changing this will Reset all scores and questions.",
        "adm_team_q_cnt": "Questions per team:",
        "adm_team_q_save": "SAVE",
        "adm_team_max": "(Max: ",
        "adm_err_auth": "Admin authentication failed or PIN changed! Please login again.",
        "adm_err_excel": "Please select an Excel file first!",
        "adm_excel_ok": "✅ Successfully loaded: {10} Easy, {20} Med, {40} Hard.",
        "adm_excel_err": "Error reading Excel: ",
        "adm_save_empty": "No question data to save!",
        "adm_save_name_prefix": "Set ",
        "adm_save_ok": "Successfully saved to Set {slotId}!",
        "adm_save_err": "Save error: ",
        "adm_load_empty": "Empty slot",
        "adm_load_ok": "📂 Loaded \"{name}\": {10} Easy, {20} Med, {40} Hard.",
        "adm_load_err": "Error: ",
        "adm_slot_txt": "{10} Easy, {20} Med, {40} Hard",
        "adm_slot_empty": "Empty",
        "adm_slot_btn": "📂 Load",
        "adm_q_label": "Question {stt}",
        "adm_q_played": " (SELECTED)",
        "adm_star_added": " HOPE STAR ⭐",
        "adm_err_q": "Error opening question: ",
        "adm_err_not_enough_q": "Current question bank doesn't have enough questions! Each team can have at most {max} questions.",
        "adm_confirm_reset": "Reset all scores?",
        "adm_confirm_team_cnt": "Changing the number of teams will RESET the entire game (scores, states). Are you sure?",
        "adm_opt_optional": "(Optional)",
        "adm_placeholder_tname": "Team Name {id}",
        "adm_placeholder_tschool": "School / Unit {id}",
        "adm_label_tavatar": "Change Team {id} avatar:",
        "adm_ts_size": "Team {id} - Size (",
        "adm_ts_overlap": "Overlap (",
        "adm_ts_offsetx": "X Offset (",
        "adm_sel_team": "-- Select Team --",
        "adm_to_played": " (Played)",
        "adm_to_force": "Force turn",
        "adm_to_end": "End turn",
        "adm_to_stats": "[Played {played}/{total} qs]",
        "adm_empty": "(Empty)",
        "adm_status_buzz_team": "🚨 {team} GOT THE BUZZER",
        "adm_status_buzz_open": "🟢 BUZZER OPEN FOR 5S",
        "adm_status_play": "PLAYING: {team} ({pts}PTS)",
        "adm_status_star": "⭐ HOPE",
        "adm_status_star_only": "SELECTED HOPE STAR ⭐",
        "adm_pt_ph": "Enter points...",
        "adm_pt_add": "ADD",
        "adm_pt_sub": "SUB",
        "adm_sb_hide": "🚫 HIDE OVERALL SCOREBOARD",
        "adm_err_ngrok_auth": "Please enter Ngrok Authtoken! (Register for free at ngrok.com)",
        "adm_ip_none": "No local IPs found.",
        "adm_net_err": "Network creation error: ",
        "adm_font_pop": "── Popular Fonts ──",
        "adm_font_all": "── All System Fonts ──",
        "adm_font_custom": " (custom)",
        "adm_modal_title": "Notification",
        "adm_modal_ok": "✅ AGREE",
        "adm_modal_cancel": "❌ CANCEL",

        // --- SCREEN / OVERLAY ---
        "scr_title": "Econova Show - Main Screen",
        "scr_audio_start": "🔊 CLICK HERE TO START",
        "scr_pts": "PTS",
        "scr_wait": "Waiting for question...",
        "scr_click_start": "👇 CLICK HERE TO START",
        "scr_unlock_audio": "This action unlocks the browser's audio system.",
        "scr_round": "ROUND 3.2: MYSTERY BOX",
        "scr_pts_empty": "-- PTS",
        "scr_pts_empty_1": "- PTS",
        "scr_pts_10": "10 PTS",
        "scr_pts_20": "20 PTS",
        "scr_pts_40": "40 PTS",

        // --- CONTESTANT ---
        "con_choose": "CHOOSE YOUR TEAM",
        "con_buzz": "🔔 BUZZ",
        "con_locked": "BUZZER LOCKED",
        "con_other": "OTHER TEAM BUZZED",
        "con_you": "YOU GOT THE BUZZER!",
        "con_wait_admin": "Waiting for admin permission...",
        "con_cheat_title": "🚨 ANTI-CHEAT WARNING!",
        "con_cheat_desc": "You have left the exam screen or pressed a forbidden key. This action has been blocked.",
        "con_cheat_btn": "I UNDERSTAND",
        "con_click_start": "CLICK HERE TO START",
        "con_req_full": "Requires Full Screen mode",
        "con_no_buzz": "YOU CANNOT BUZZ",
        "con_title": "Econova Show - Contestant",
        "con_access_denied": "Access denied. Please open the app from the main executable file (.exe).",
        "con_pts_10": "10 PTS",
        "con_pts_20": "20 PTS",
        "con_pts_40": "40 PTS",
        "con_claimed": " (Selected)",
        "con_session_ended": "The session has ended or PIN has changed. Please close the app and reopen!",
        "con_team_count_changed": "The organizers have changed the number of teams. Please select a team again!",
        "con_buzz_open": "BUZZER OPEN!",
        "con_buzz_exclaim": "🔔 BUZZ NOW!",
        "con_team_placeholder": "TEAM",
        "con_school_placeholder": "School",
        "con_your_turn": "YOUR TURN",

        // --- SCOREBOARD ---
        "sb_choose": "CHOOSE SCOREBOARD TEAM",
        "sb_title": "PERSONAL SCOREBOARD",
        "sb_page_title": "Econova Show - Scoreboard",
        "sb_access_denied": "Access denied. Please open the app from the main executable file (.exe).",
        "sb_team_count_changed": "The organizers have changed the number of teams. Please select a team again!"
    }
};

let currentAppliedLang = null;
function applyTranslations(lang) {
    if (!lang) lang = currentGlobalLang || 'vi';
    if (currentAppliedLang === lang) return;
    currentAppliedLang = lang;
    const dict = I18N[lang] || I18N['vi'];
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) {
            if (el.tagName === 'INPUT' && (el.type === 'text' || el.type === 'number')) {
                if (el.placeholder !== dict[key]) el.placeholder = dict[key];
            } else if (el.tagName === 'INPUT' && el.type === 'button') {
                if (el.value !== dict[key]) el.value = dict[key];
            } else {
                if (el.innerHTML !== dict[key]) el.innerHTML = dict[key];
            }
        }
    });
}

function t(key, lang) {
    const dict = I18N[lang] || I18N['vi'];
    return dict[key] || key;
}

// Global language variable for pages without socket state
let currentGlobalLang = localStorage.getItem('econova_lang') || 'vi';

// Helper to switch language locally
function setLocalLanguage(lang) {
    currentGlobalLang = lang;
    localStorage.setItem('econova_lang', lang);
    applyTranslations(lang);
}
